### ISSUE TITLE
.Wait() never returns

### ISSUE THREAD

**Issue by mpelley** [TimHanewich/Yahoo.Finance#2]
Here is my code, similar to your test/example:
            var provider = new HistoricalDataProvider();
            provider.DownloadHistoricalDataAsync("GLD", new DateTime(2020, 1, 1), DateTime.Today).Wait();
            var status = provider.DownloadResult;
The third line is never hit.  I waited over 10 minutes.  How long should I expect to wait?  Is this library still working?  Did yahoo do anything to stop this?

**Comment by TimHanewich** [comment]
Hi Mike, thanks for reaching out. Which package version are you using? This method was indeed causing an issue in the past but I fixed it recently. With [package version 4.1.0](https://www.nuget.org/packages/Yahoo.Finance/4.1.0):

`public static async Task GetHistoricalDataExample()
        {
            HistoricalDataProvider hdp = new HistoricalDataProvider();
            await hdp.DownloadHistoricalDataAsync("MSFT", new DateTime(2018, 1, 1), new DateTime(2018, 2, 1));
            foreach (HistoricalDataRecord rec in hdp.HistoricalData)
            {
                Console.WriteLine(rec.Date.ToShortDateString() + " - " + rec.AdjustedClose.ToString());
            }
        }`

Resulting output:

1/2/2018 - 82.004974
1/3/2018 - 82.38662  
1/4/2018 - 83.11174  
1/5/2018 - 84.14217  
1/8/2018 - 84.22803  
1/9/2018 - 84.1708   
1/10/2018 - 83.78915 
1/11/2018 - 84.037224
1/12/2018 - 85.48744 
1/16/2018 - 84.294815
1/17/2018 - 86.00265 
1/18/2018 - 85.96451 
1/19/2018 - 85.86909 
1/22/2018 - 87.40518 
1/23/2018 - 87.68189 
1/24/2018 - 87.605545
1/25/2018 - 88.09213 
1/26/2018 - 89.74273 
1/29/2018 - 89.60915 
1/30/2018 - 88.48332 
1/31/2018 - 90.64913

**Comment by TimHanewich** [comment]
Class library tested and still working as expected. Please let me know if you continue having troubles @mpelley
